src/android/app/src/main/java/org/citra/citra_emu/applets/SoftwareKeyboard.java

Fixes [#5359](https://github.com/citra-emu/citra/issues/5359) for android
Equivalent of PR [#5362](https://github.com/citra-emu/citra/pull/5362) in citra-emu/citra
Apps always return 3 strings, even if there is no custom text, so the index should be constant for each button.
The "OK" button is always at index 2.

android: applets: Fix button order received from button_text

---

src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.java

Should fix #47
Originally, since the ACTION_MASK was not applied, the switch case only worked when the pointer index was 0. It should now fix the issue where touches on the 3DS touch screen were not detected.

Touchscreen Fix

---

src/video_core/renderer_opengl/gl_shader_gen.cpp

A pretty minor change so I haven't tested it whole lot, only checked to see if MH4U goes in-game(and it does)

fix implicit type conversion error for gles

---

src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableJoystick.java
src/android/app/src/main/java/org/citra/citra_emu/utils/EmulationMenuSettings.java
src/android/app/src/main/res/menu/menu_emulation.xml
src/android/app/src/main/res/values/strings.xml

Based on dolphin-emu/dolphin#7186.
Adds a new menu option to Configure Controls which configures whether the circle pad re-centers or not.

Make touch joystick re-centering configurable

---

src/android/app/src/main/AndroidManifest.xml
src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.java
src/android/app/src/main/java/org/citra/citra_emu/utils/ForegroundService.java

Resolves #65
Due to how Android handles applications in the background, starting a foreground service is the only way to prevent the system from clearing the app from memory when minimized.
This is also necessary to keep the running notification showing. I noticed that commit b1434f76722959c9c9a4fbcf061c2e78954869db removed the `.setOngoing` property. This had to be re-enabled or else the notification could be manually dismissed, which would imply to the user that emulation is not running (when app is minimized) while the service is still running.

android: frontend: Start a service to keep the persistent notification

---

src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableDpad.java

DPad buttons behave similarly to joystick, you can slide the finger across it to change direction. Might add an option to disable, if necessary. I didn't implement recentering because it seemed more confusing, let me know if I should add it.

Allow sliding finger across DPad to change direction

---

src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/renderer_opengl/gl_rasterizer_cache.h

The games are trying to sample and draw to the same surface at the same time, so we can just create duplicate image to use for sampling. I didn't notice any significant effect on performance.

video_core/GLES: fix issues cause by missing glTextureBarrier

---

src/android/app/build.gradle

Current there is no version name set for the app, I feel like this might have been somehow lost during a merge.
So brought back the version name.
Edit: Fixes #15 
<details>
<summary>Screenshots</summary>
</details>

Version name

---

src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableDpad.java

Fixes an issue where the d-pad gets activated when touching anywhere on the screen right after rotation.

android : InputOverlayDrawableDpad.java: Initialize mTrackId to -1

---

src/video_core/renderer_opengl/gl_shader_gen.cpp

This works around an apparent driver bug on the Shield TV where it seems unable to construct an array of vec3's directly from the results of textureLod calls.
This is the 2nd of 3 PR's needed to make Citra work on the Nvidia Shield TV
The 1st required PR is #107

Shield TV driver bug workaround

---

src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.java
src/android/app/src/main/jni/button_manager.cpp
src/android/app/src/main/jni/button_manager.h
src/android/app/src/main/jni/config.cpp

This was a doozy to track down.
This fixes two issues that prevented N3DS controls from working in certain situations.
1. default_buttons in config.cpp was missing the Debug and GPIO14 buttons, meaning ZL got mapped to Home and ZR got mapped to nothing
This adds them to the array.
(Idk how these "7XX" numbers were picked, please give feedback)
2. button_manager.cpp would return as soon as a button matching the button_id/axis_id/analog_id was found
However, both IR_RST and ExtraHID create ZL and ZR button devices (I believe this is ultimately a result of intended behavior to allow platforms to map the same key to different actions)
This means the entire array of mappings must be searched.

Fix the N3DS controls

---

src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableJoystick.java
src/android/app/src/main/jni/native.cpp

This makes the touch screen circle pad actually bounded by a circle rather than a box, and ensures all inputs passed to the emulator actually meet the assumptions of the HID service, so gamepad input is clamped correctly too.

Clamp the circle pad more correctly

---

src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.java
src/android/app/src/main/jni/emu_window/emu_window.cpp
src/android/app/src/main/jni/emu_window/emu_window.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/jni/native.h
src/core/frontend/emu_window.cpp
src/core/frontend/emu_window.h

Add proper multitouch tracking so buttons and touchscreen can be interacted at the same time.
this should fix #87 and maybe some other related issues.
There are a couple of problems remaining-
1. Buttons overlayed on the touchscreen, this behaviour is unchanged from previous versions and the touch triggers both the button and wherever the 3DS screen is touched
2. The latest touch pointer is given priority and tracked when it 'presses' the 3DS touchscreen, not sure if this is the best thing to do, need some feedback on this.

Touchscreen fix v2

---

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
src/video_core/renderer_opengl/texture_downloader_es.cpp
src/video_core/renderer_opengl/texture_downloader_es.h

The depth stencil shader used by ds_to_color.frag currently requires the "GL_ARM_shader_framebuffer_fetch_depth_stencil" which is not supported on Tegra devices at the moment, and reportedly the Nexus 6P too.
As per the conversation with @BreadFish64, this has been disabled by adding a parameter to the constructor to allow disabling depth stencil support by the caller.
This is the 3rd PR required to fix the Shield TV.

Disable deptch stencil shader in texture_downloader_es for now

---

src/android/app/src/androidTest/java/org/citra/citra_emu/ExampleInstrumentedTest.java
src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.java
src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.java
src/android/app/src/main/jni/emu_window/emu_window.cpp
src/android/app/src/main/jni/emu_window/emu_window.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/test/java/org/citra/citra_emu/ExampleUnitTest.java
src/android/build.gradle

Reverts citra-emu/citra-android#92
@weihuoya we need to revert this one, because it looks like the UI is now laggy when emulation is not fullspeed. I would not expect this to be the case, since presentation is on its own thread. Can you take a look, and resubmit a PR if you can fix this? Thank you.

Revert "Presenting in ui thread"

---

src/android/app/src/main/AndroidManifest.xml

This should help display the app on the whole screen on 21:9 devices like the Xperia Z5.
Hopefully fixes https://github.com/citra-emu/citra-android/issues/141.

AndroidManifest: Increase the maximum aspect ratio

---

src/video_core/renderer_opengl/renderer_opengl.cpp

Fixes #144.
Waiting here on free_queue causes emulation to be limited to 100%. However, I don't know if this is the correct placement for this, so should it be moved to `TryGetPresentFrame()` @weihuoya? The issue is fixed on both cases.

Wait on present_queue instead of free_queue

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/Settings.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivity.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/utils/SettingsFile.java
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/res/values/arrays.xml
src/android/app/src/main/res/values/strings.xml
src/core/frontend/emu_window.cpp
src/core/frontend/framebuffer_layout.cpp
src/core/frontend/framebuffer_layout.h
src/core/settings.h
src/video_core/renderer_opengl/renderer_opengl.cpp

Ported the frontend changes from citra-emu/citra/pull/5018
Cardboard VR is based on hrydgard/ppsspp/pull/12449. Screen size and placement can be adjusted from the settings. The screens are never stretched, so portrait mode may seem a bit small on the default settings.
Also made the framebuffer layout get updated after closing the settings. This fixes an issue with the default layout getting applied (both before and after this PR)
[Preview of updated Graphics settings](https://imgur.com/a/YdUtiOh) (I'm open to suggestions about this)
[Preview of Cardboard VR mode](https://imgur.com/a/86gsxwd)

Add UI for Stereoscopy settings and implement Cardboard VR

---

src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.java
src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableDpad.java
src/android/app/src/main/java/org/citra/citra_emu/utils/EmulationMenuSettings.java
src/android/app/src/main/res/menu/menu_emulation.xml
src/android/app/src/main/res/values/strings.xml

As requested a while ago by @bunnei . Sorry for the delay. Decreased sensitivity to .5 and implemented option to enable sliding across dpad to change direction.

Implemented switch for sliding finger across dpad + fixed sensitivity

---

src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.java
src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.java
src/android/app/src/main/jni/emu_window/emu_window.cpp
src/android/app/src/main/jni/id_cache.cpp
src/android/app/src/main/jni/id_cache.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/jni/native.h
src/android/app/src/main/res/layout/dialog_checkbox.xml
src/android/app/src/main/res/menu/menu_emulation.xml
src/android/app/src/main/res/values/strings.xml
src/video_core/gpu.cpp
src/video_core/gpu.h
src/video_core/gpu_thread.cpp
src/video_core/gpu_thread.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/video_core.cpp

This adds the savestates feature to Citra Android.
The first commit features several changes to make savestates actually work with the android frontend and async GPU. The second commit adds the frontend for savestates (for now, this is a simple menu). The third commit adds code to report and handle core errors (including save/load errors), similar to what we do in the Qt frontend.
Screenshots:
Notes:
1. The menu is not shown for applications without a Title ID, like 3DSX homebrews.
1. Java code in this PR is not properly formatted because I'm not sure what style we are following (it's not clang format)
1. ~~We need to inform users that savestates are not meant to be reliable. There are several possible ways of doing this. We can show a popup when `Save State` is used for the first time. …

Add savestates feature

---

src/android/app/src/main/jni/emu_window/emu_window.cpp
src/core/frontend/emu_window.h
src/video_core/renderer_base.h
src/video_core/renderer_opengl/frame_dumper_opengl.cpp
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_opengl/renderer_opengl.h

Keeps compatibility with the other frontends (Qt, SDL) while using the choreographer and ensuring the Android UI remains responsive.
The main difference is instead of not swapping if no frame is available, present the previous one like all other frontends do. The timeout is set to 0 because it is critical that we do not block the choreographer. This doesn't seem to really cause any problems that I can see.

Partial revert of Choreographer UI thread implementation

---

src/android/app/src/main/java/org/citra/citra_emu/disk_shader_cache/DiskShaderCacheProgress.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/utils/SettingsFile.java
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/jni/id_cache.cpp
src/android/app/src/main/jni/id_cache.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/res/layout/dialog_progress_bar.xml
src/android/app/src/main/res/values/strings.xml
src/video_core/renderer_base.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h
src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
src/video_core/renderer_opengl/gl_shader_disk_cache.h
src/video_core/renderer_opengl/gl_shader_manager.cpp
src/video_core/renderer_opengl/gl_shader_manager.h
src/video_core/renderer_opengl/gl_shader_util.cpp

Adds disk cache for conventional/non-separable shaders, additionally add multi-threading for loading the Transferable cache, likely adds additional load time on desktop, since we don't check if the precompiled shader is already present in the cache (I'll probably address that in a later PR).
The progress dialog implementation feels jank atm, so if anyone knows a better way I would appreciate it.

Add Disk shader cache 

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivity.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivityPresenter.java
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivityView.java

Fixes the behavior where the settings activity would go back to the top-level menu after switching to a different app and back.
This is the same change as https://github.com/dolphin-emu/dolphin/pull/9009/commits/05e49b13ef5f28c0fe8705030bdd2fa975d02aff. I'm not sure if backporting changes from Dolphin is something you do often or not, but I saw that you had this problem that has been fixed in Dolphin and thought I might as well backport the fix :)

Fix SettingsActivity back stack behavior after stop+start
